# Generated by Django 4.1.3 on 2022-11-30 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kapsylgram', '0002_comment_like_message_notification_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('another_user', models.ManyToManyField(related_name='another_user', to='kapsylgram.user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kapsylgram.user')),
            ],
        ),
    ]
