# Generated by Django 4.1.3 on 2022-11-30 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kapsylgram', '0003_user_pfp_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocking', models.ManyToManyField(related_name='blocking', to='kapsylgram.user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kapsylgram.user')),
            ],
        ),
    ]
