# Generated by Django 4.1.3 on 2022-12-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapsylgram', '0004_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='kapsylgram.user'),
        ),
    ]
