# Generated by Django 4.1.3 on 2022-12-15 16:25

from django.db import migrations, models
import django.db.models.deletion
from datetime import date

def create_data(apps, schema_editor):
    User = apps.get_model('kapsylgram', 'User')
    joey = User(username="Jjoeysilver", password="iamjoey", displayname = "Joe Silver", email = "joey@silver.gmail.com")
    joey.save()
    Post = apps.get_model('kapsylgram', 'Post')
    Post(postedBy = joey, content = "this is a post by me JOEY BABYYYY", postedWhen = date.today()).save()

class Migration(migrations.Migration):

    dependencies = [
        ('kapsylgram', '0005_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posttype',
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.RunPython(create_data),
    ]
