# Generated by Django 4.1.3 on 2022-12-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapsylgram', '0006_remove_post_posttype_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notifications',
            field=models.ManyToManyField(blank=True, to='kapsylgram.notification'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
