# Generated by Django 4.1.3 on 2023-01-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapsylgram', '0011_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentWhen',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='postedWhen',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
