# Generated by Django 4.1.3 on 2023-01-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapsylgram', '0012_alter_comment_commentwhen_alter_post_postedwhen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, to='kapsylgram.comment'),
        ),
    ]
