# Generated by Django 4.1.3 on 2023-01-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapsylgram', '0015_userprofile_is_active_userprofile_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
